### ISSUE TITLE
Questions about operator

### ISSUE THREAD

**Issue by jferr** [instana/instana-agent-operator#37]
We are a current instana customer and are not currently using the operator...but I tried it out on a cloud kuber instance and it seems to work great.
-Does it/can it automatically update the agents as new ones are released?  If yes are there details around this...is it timed/triggered somehow?  Can we limit it to a time window
-Is it production "ready?"

**Comment by mdonkers** [comment]
Hi @jferr ,

Not sure if this question is still applicable? We recently released a totally new Operator (version 2.0.0 and up). So to answer your questions based on that;
- Because the Agent daemonset is configured with container `pullPolicy` : `always` by default, whenever you make a configuration change or update the Operator, it will also update the Agent containers. It won't automatically check on a regular basis whether there are new images though. Also via configuration you can 'pin' the image to a specific version. By default the Dynamic Agent is installed, which will automatically update all internal sensors on a daily basis. So while then the base installation is not updated, all sensors are.

- yes, our Operator is "production ready". Because of the rebuild in Golang there might still be some minor issues. But we did rigorous testing and will also fix issues soon as possible. For actual issues it would be better to file them via our regular ticket system instead of here, because its better tracked.
