### ISSUE TITLE
Adding the ability to set the mirror parameter for the helm-repository

### ISSUE THREAD

**Issue by ivanovpavel1983** [instana/instana-agent-operator#96]
I cannot start the agent through the operator on hosts where there is no Internet access.

{"level":"info","ts":1677490206.879658,"logger":"instana.agent.controller.helm-reconcile","msg":"...Unable to get an update from the \"instana-agent\" chart repository (https://agents.instana.io/helm):\n\tGet \"https://agents.instana.io/helm/index.yaml\": dial tcp 35.186.234.48:443: connect: connection timed out\n"}

{"level":"error","ts":1677490206.879732,"logger":"instana.agent.controller.helm-reconcile","msg":"Failure loading or validating Instana Agent Helm Chart, cannot proceed installation","error":"stat : no such file or directory","stacktrace":"github.com/instana/instana-agent-operator/controllers.(*InstanaAgentReconciler).Reconcile\n\t/workspace/controllers/instanaagent_controller.go:240\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214"}

Is it possible to add a repository mirror option to the internal network?

**Comment by konrad-ohms** [comment]
Hey @ivanovpavel1983,
this issue is open for quite a while, not sure if it is still relevant.
Please note that the proper way to receive support for the Instana Agent Operator is thru IBM Support.
Anyways, I wanted to give you a hint here, also if others hit a similar scenario.

It is possible to install the Agent via Helm or Kubernetes Operator.
We describe the process for helm in our docs: [Preparing for an air-gapped installation](https://www.ibm.com/docs/en/instana-observability/current?topic=agents-installing-kubernetes#installing-the-host-agent-in-an-air-gapped-environment).

In essence, you can pull the images via docker/skopeo to a different internal registry and overwrite the image references via properties in helm or the operator deployment.yaml and the agent custom resource.
